# Generated by Django 6.0 on 2025-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=180)),
                ("last_name", models.CharField(max_length=200)),
                ("email_id", models.CharField(max_length=200)),
                ("phone_no", models.IntegerField()),
                ("message", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email_id"], name="mydjangoapp_email_i_08f403_idx"
                    )
                ],
            },
        ),
    ]
